### ISSUE TITLE
ohmyzsh git plugin

### ISSUE THREAD

**Issue by ben-barbier** [PAPAMICA/terminal#1]
Hello !

Thx for your sharing 🚀!

I took a lot of inspiration from it to update mine.

FYI, we could replace your git alias (https://github.com/PAPAMICA/terminal/blob/main/zshrc#L51) by the ohmyzsh git plugin (https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git).

🎁

**Comment by PAPAMICA** [comment]
Thanks you so mush for this plugins !

Very good job 😎
